package com.fansauchiwa

const val NAME_TEMPLATE_LAST_NAME_PLACEHOLDER_TEXT = "みょうじ"
const val NAME_TEMPLATE_FIRST_NAME_1_PLACEHOLDER_TEXT = "名"
const val NAME_TEMPLATE_FIRST_NAME_2_PLACEHOLDER_TEXT = "前"
const val NAME_TEMPLATE_HONORIFIC_PLACEHOLDER_TEXT = "くん"
